### ISSUE TITLE
SystemException undefined for OS X Mojave build

### ISSUE THREAD

**Issue by neozeed** [lenticularis39/axpbox#14]
`[ 75%] Building CXX object CMakeFiles/axpbox.dir/src/base/Semaphore.cpp.o
In file included from /Users/jsteve/src/axp2/src/base/Semaphore.cpp:77:
/Users/jsteve/src/axp2/src/base/Semaphore_POSIX.cpp:112:11: error: use of
      undeclared identifier 'SystemException'
    throw SystemException("cannot create semaphore (condition)");
`

Pretty sure I have the latest stuff..  Although I like my 32bit too much to go all the way to the new stuff.

TrashCan:build jsteve$ uname -a
Darwin TrashCan.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64

TrashCan:build jsteve$ cc -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by neozeed** [comment]
I changed it to CSystemException ... maybe it's a typo?

**Comment by lenticularis39** [comment]
> I changed it to CSystemException ... maybe it's a typo?

Oops, it definitely is - that came in when I updated the code with the new version from POCO (the es40 code prefixes everything in POCO with C-).
