### ISSUE TITLE
autocreate filesize works up to 2 GB disks

### ISSUE THREAD

**Issue by RaymiiOrg** [lenticularis39/axpbox#31]
Somethig is wrong with autocreating disks, I got an email from an OpenVMS system manager at the belgian railways with a reproduction scenario. I did recently change the disk creation to fix #19 , so I'll have a look myself first.

- 0 up to 2000 M = OK
- 2000M up to 4000M = negative filesize 
- 4000M up to 6000M = file created, but - 2 GB in size
- 6000M up to 8000M = negative filesize again
- 9000M up to 10000M = file created, but - 8 GB in size

## 1 GB, es40.cfg

	autocreate_size = 1000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) 1000MB file disk-0.img created
	pci0.15(ali_ide).disk0.0(file): Mounted file disk-0.img, 2048000 512-byte blocks, 2560/16/50.

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 1048576000 Nov 15 07:31 disk-0.img

## 2 GB, es40.cfg

	autocreate_size = 2000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) 2000MB file disk-0.img created
	pci0.15(ali_ide).disk0.0(file): Mounted file disk-0.img, 4096000 512-byte blocks, 5120/16/50.

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 2097152000 Nov 15 07:33 disk-0.img

## 3 GB es40.cfg

	autocreate_size = 3000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) -1096MB file disk-0.img created

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 0 Nov 15 07:34 disk-0.img

## 4 GB es40.cfg

	autocreate_size = 4000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) -96MB file disk-0.img created

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 0 Nov 15 07:37 disk-0.img

## 5 GB es40.cfg

	autocreate_size = 5000M;
	
Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) 904MB file disk-0.img created
	pci0.15(ali_ide).disk0.0(file): Mounted file disk-0.img, 1851392 512-byte blocks, 3616/16/32.

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 947912704 Nov 15 07:38 disk-0.img

## 6 GB es40.cfg

	autocreate_size = 6000M;
		
Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) 1904MB file disk-0.img created
	pci0.15(ali_ide).disk0.0(file): Mounted file disk-0.img, 3899392 512-byte blocks, 7168/16/34.

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 1996488704 Nov 15 07:40 disk-0.img

## 7 GB es40.cfg

	autocreate_size = 7000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) -1192MB file disk-0.img created

## 8 GB es40.cfg

	autocreate_size = 8000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) -192MB file disk-0.img created

## 9 GB es40.cfg

	autocreate_size = 9000M;

Result:

	pci0.15(ali_ide).disk0.0(file): file does not exist: disk-0.img
	pci0.15(ali_ide).disk0.0(file) 808MB file disk-0.img created
	pci0.15(ali_ide).disk0.0(file): Mounted file disk-0.img, 1654784 512-byte blocks, 3232/16/32.

	$ \ls -la disk-0.img 
	-rw-rw-r-- 1 remy remy 847249408 Nov 15 07:42 disk-0.img

**Comment by RaymiiOrg** [comment]
Okay this was my own fault, configurator uses an u64 and I put it into an int. Sorry, my bad. Made a merge request to correct it: #32

**Comment by lenticularis39** [comment]
That's why I should refactor the code and add unit tests to prevent such bugs from happening. In my experience there is a lot of possible bugs that could be easily detected, but aren't very well visible to the human eye.
