### ISSUE TITLE
Build needs C++14 feature hint on MacOS

### ISSUE THREAD

**Issue by mvorl** [lenticularis39/axpbox#37]
When building on MacOS 10.13.6 using MacPort's CMake 3.18.4 and Apple LLVM version 10.0.0 (clang-1000.11.45.5), it fails due to
```
[  8%] Building CXX object CMakeFiles/axpbox.dir/src/AlphaCPU.cpp.o
In file included from .../axpbox/src/AliM1543C.cpp:266:
.../axpbox/src/AliM1543C.hpp:211:20: error: function definition does not declare parameters
  std::atomic_bool myThreadDead{false};
                   ^
.../axpbox/src/AliM1543C.cpp:496:21: **error: no member named 'make_unique' in namespace 'std'**
    myThread = std::make_unique<std::thread>([this](){ this->run(); });
               ~~~~~^
.../axpbox/src/AliM1543C.cpp:496:44: error: expected '(' for function-style cast or type construction
    myThread = std::make_unique<std::thread>([this](){ this->run(); });
                                ~~~~~~~~~~~^
.../axpbox/src/AliM1543C.cpp:496:46: error: expected expression
    myThread = std::make_unique<std::thread>([this](){ this->run(); });
                                             ^
```
Fix is to request C++14 features:
`target_compile_features(axpbox PUBLIC cxx_std_14)`

With this, there are only a few warnings about type mismatches between long and long long arguments.

Thanks for the great work on this!

**Comment by RaymiiOrg** [comment]
This is handled in #35 - could you please try building that branch? I'm only able to test on os x via github actions (no Mac myself), so I'm curious if axpbox runs after it compiles.

We're trying to keep it on c++ 11, there's a bit of explanation on the wiki on that: https://github.com/lenticularis39/axpbox/wiki#platform-support

**Comment by mvorl** [comment]
Doesn't fix it in my environment:
```
[  8%] Building CXX object CMakeFiles/axpbox.dir/src/AlphaCPU_ieeefloat.cpp.o
In file included from .../axpbox/src/AliM1543C.cpp:266:
In file included from .../axpbox/src/AliM1543C.hpp:142:
In file included from .../axpbox/src/PCIDevice.hpp:60:
In file included from .../axpbox/src/SystemComponent.hpp:88:
In file included from .../axpbox/src/Configurator.hpp:90:
In file included from .../axpbox/src/StdAfx.hpp:313:
.../axpbox/src/make_unique.hpp:9:31: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
template<typename T, typename ...Args>
                              ^
.../axpbox/src/make_unique.hpp:10:37: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
std::unique_ptr<T> make_unique( Args&& ...args )
                                    ^
```
But additionally telling CMake fixes it
`target_compile_features(axpbox PUBLIC cxx_std_11)`

Thanks!

**Comment by RaymiiOrg** [comment]
> But additionally telling CMake fixes it
> `target_compile_features(axpbox PUBLIC cxx_std_11)`
> 

Cool! You can close the bug if it's fixed for you now.

In the ci build the following flags are used for os x :

    -DCMAKE_CXX_FLAGS="-Wall -Wc++11-extensions -Wc++11-long-long -Wc++11-extra-semi -std=c++11 -stdlib=libc++"


Can you confirm that the compiled binary actually runs and works? Not related to this issue but I'm having a bit of trouble with the ci and no Mac to reproduce on.

**Comment by mvorl** [comment]
Yepp, I can confirm it just booted mv 53C810-based VMS 8.3 disk.

The flags generated by CMake are
`CXX_FLAGS =  -O3 -march=native -DNDEBUG -O3 -DNDEBUG -std=gnu++11`

Now looking into how to integrate the MacPorts include & lib directories into the build (so that it can find SDL and X11).
