### ISSUE TITLE
Build fails on MacOS BigSur ARM64 (Apple M1) 

### ISSUE THREAD

**Issue by DoktorCranium** [lenticularis39/axpbox#52]
All dependencies needed are natively compiled on BigSur ARM64  (clang-1200.0.32.28) 
cmake finishes 
build fails on the following

```
[  1%] Building CXX object CMakeFiles/axpbox.dir/src/AliM1543C.cpp.o
In file included from /Users/user/SRC/axpbox/src/AliM1543C.cpp:270:
In file included from /Users/user/SRC/axpbox/src/AliM1543C.hpp:144:
In file included from /Users/user/SRC/axpbox/src/PCIDevice.hpp:62:
In file included from /Users/user/SRC/axpbox/src/SystemComponent.hpp:90:
In file included from /Users/user/SRC/axpbox/src/Configurator.hpp:92:
In file included from /Users/user/SRC/axpbox/src/StdAfx.hpp:315:
/Users/user/SRC/axpbox/src/make_unique.hpp:34:31: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
template<typename T, typename ...Args>
                              ^
/Users/user/SRC/axpbox/src/make_unique.hpp:35:37: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
std::unique_ptr<T> make_unique( Args&& ...args )
                                    ^
In file included from /Users/user/SRC/axpbox/src/AliM1543C.cpp:270:
/Users/user/SRC/axpbox/src/AliM1543C.hpp:213:20: error: function definition does not declare parameters
  std::atomic_bool myThreadDead{false};
                   ^
/Users/user/SRC/axpbox/src/AliM1543C.cpp:500:46: error: expected expression
    myThread = std::make_unique<std::thread>([this](){ this->run(); });
                                             ^
/Users/user/SRC/axpbox/src/AliM1543C.cpp:997:5: error: use of undeclared identifier 'myThreadDead'; did you mean 'myThread'?
    myThreadDead.store(true);
    ^~~~~~~~~~~~
    myThread
/Users/user/SRC/axpbox/src/AliM1543C.hpp:212:32: note: 'myThread' declared here
  std::unique_ptr<std::thread> myThread;
                               ^
/Users/user/SRC/axpbox/src/AliM1543C.cpp:997:18: error: no member named 'store' in 'std::__1::unique_ptr<std::__1::thread, std::__1::default_delete<std::__1::thread>
      >'
    myThreadDead.store(true);
    ~~~~~~~~~~~~ ^
/Users/user/SRC/axpbox/src/AliM1543C.cpp:1437:7: error: use of undeclared identifier 'myThreadDead'
  if (myThreadDead.load())
      ^
2 warnings and 5 errors generated.
make[2]: *** [CMakeFiles/axpbox.dir/build.make:82: CMakeFiles/axpbox.dir/src/AliM1543C.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/axpbox.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by RaymiiOrg** [comment]
Thanks for reporting! I don't have an M1 device to test on, do you perhaps know if this issue also comes up in non-M1 big sur? Our github actions runner uses 10.15, and except for a vm, that is the only Mac hardware I can test with. I'm asking because if so, I can try to install a big sur x64 vm to test with.

**Comment by DoktorCranium** [comment]
I only have the M1 BigSur sorry

**Comment by lenticularis39** [comment]
Looking at the warnings it seems to me like C++11 isn't enabled, but that would be strange considering it's Clang 12. Maybe I can get some information on my Catalina VM - I'll try that.

**Comment by stottsc** [comment]
I **just** built axpbox successfully on MacBook Air M1 (commit 3c7b9e4). It required building with the LLVM from Homebrew. 

I read somewhere (wish I could remember where) that the clang shipped with Xcode is missing support for a few C++ extensions. I can't remember the specifics...

**Comment by stottsc** [comment]
Sorry, just figured it out. It **works** with the Xcode clang, but you have to tell cmake to tell clang that we require C++11.

"set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)" goes at the top of the CMakeLists.txt

I'll do a pull request.

Verified to build on Catalina (Intel), and Big Sur (M1)

**Comment by lenticularis39** [comment]
> Sorry, just figured it out. It **works** with the Xcode clang, but you have to tell cmake to tell clang that we require C++11.
> 

Oh, that's weird. I guess it has something to do with internal use of the LLVM toolchain by Apple - as we know from the opening of Solaris building old closed-source code, especially on the system level, tends to be tricky.

**Comment by DoktorCranium** [comment]
Yes - just tried and it does build with Stottsc's patches to the CMakeLists.txt on the M1

**Comment by lenticularis39** [comment]
The C++11 patch is merged, along with a fix of a bug in the Tulip emulation, which improves networking, so you can just use the main branch now.

**Comment by RaymiiOrg** [comment]
> The C++11 patch is merged, along with a fix of a bug in the Tulip emulation, which improves networking, so you can just use the main branch now.

Oh that's great! Thanks! The cherry picking turned out to be quite difficult to do properly and tidy.

Do you have preference for a versioning scheme? Is semver (and starting with 1.0.0) okay or just 0.1 and increment whenever there is a new release?
