### ISSUE TITLE
Offer of patches

### ISSUE THREAD

**Issue by promovicz** [lenticularis39/axpbox#55]
Hello folks!

I have recently noticed this project through Twitter post. A few years ago I did some hacking on es40, mostly compilation fixes and the like. If you are interested then you could look through this commit log:

https://github.com/retroprom/es40/commits/promovicz/master

Feel free to grab whatever you need!

Greetings
  prom

**Comment by DoktorCranium** [comment]
I can confirm that your patches work and compile nicely on the Mac M1 
Although I had to link against pkgsrc SDL1.x  (linker bailed out with errors when linking against SDL2)

**Comment by RaymiiOrg** [comment]
I'll compare the branches and give it a try tomorrow. Let's see what kind of pull request I can come up with.

**Comment by RaymiiOrg** [comment]
Except for the build system changes (autoconf is replaced by cmake here), parenthesis and const char* vs. std::string initialization I've ported over the commits in merge request #56 . It's up to Tomáš  now to check what he want's to keep.

**Comment by RaymiiOrg** [comment]
Tomáš Was fast, thanks both! If you have any more contributions feel free to open up a merge request or issue again.
