### ISSUE TITLE
Floating point copyright notices

### ISSUE THREAD

**Issue by archivisth** [lenticularis39/axpbox#64]
At the tail end of the two floating point modules (IEEE and VAX), there's a brief notice that code was modeled on or incorporated from the SimH Alpha code, and a simple copyright 2003.

The SimH code is licensed under the most permissive open source license (MIT X11/JPEG style), but it does have one requirement: that derivative works reproduce the original copyright notice in full. This is for protection of the derivative work, showing that it does not derive from a more restrictive license type, such as GPL.

The SimH Alpha modules are in the SimH GitHub repository and are the best place to get the exact wording.

**Comment by RaymiiOrg** [comment]
I assigned myself to do this but @mvorl already handled it in #65 , so let's away @lenticularis39's review of that merge request, after which the correct notices are in place.

**Comment by RaymiiOrg** [comment]
@lenticularis39 merged the pull request.
