### ISSUE TITLE
Spurious "set multiple mode" messages

### ISSUE THREAD

**Issue by gmpalter** [lenticularis39/axpbox#69]
I'm trying to install Tru64 UNIX 5.1B onto an IDE disk. (The installation is actually working although very slowly.) I'm seeing the following message appear numerous times.
```
Set multiple mode: sector_count = 128
```

I believe this message should be conditional based on `DEBUG_IDE_MULTIPLE` in `AliM1543C_ide.cpp`. (I'd submit a PR but I'm not yet ready to go there.)

For the record, I'm trying this on an M1 Mac mini (i.e., Apple silicon or ARM64).

**Comment by lenticularis39** [comment]
You are right, that message definitely should be conditioned by a debug macro.
